@Url = http://localhost:3000
@authtoken = {{authenticate.response.body.token}}
@refreshtoken = {{authenticate.response.body.refreshToken}}

#Auth
### authenticate
# @name authenticate
POST {{Url}}/auth
Content-Type: application/json

{
    "email": "thalyson@gmail.com",
    "password": "123456"
}
### reauthenticate
# @name reauthenticate
POST {{Url}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshtoken}}"
}


# RECADOS
### GET  {{Url}}/recados
GET  {{Url}}/recados
Authorization: Bearer {{authtoken}}
###
GET  {{Url}}/recados/
?limit=
&offset=2
###
GET  {{Url}}/recados/68
###
POST  {{Url}}/recados
Authorization: Bearer {{authtoken}}
Content-Type: application/json

{
    "texto": "Texto novo",
    "paraId": 22
}
####
PATCH   {{Url}}/recados/69
Authorization: Bearer {{authtoken}}
Content-Type: application/json

{
    "texto": "editado",
    "lido": false
}
###
DELETE  {{Url}}/recados/68
Authorization: Bearer {{authtoken}}




#Pessoa
###
POST  {{Url}}/pessoas
Content-Type: application/json

{
    "email": "thalyson@gmail.com",
    "password": "123456",
    "nome": "abelha",
    "RoutePolicies": ["createRecado", "findAllRecados"]
}
###
PATCH   {{Url}}/pessoas/17
Authorization: Bearer {{authtoken}}
Content-Type: application/json

{
    "email": "thalyson@gmail.com",
    "password": "123456"
}
###
GET  {{Url}}/pessoas
Authorization: Bearer {{authtoken}}
###
GET  {{Url}}/pessoas/23
Authorization: Bearer {{authtoken}}

###
DELETE    {{Url}}/pessoas/21
Authorization: Bearer {{authtoken}}


#Upload
### Foto do usuário
POST {{Url}}/pessoas/upload-picture
Authorization: Bearer {{authtoken}}
Content-Type: multipart/form-data; boundary=----BoundaryDelimitadorHttp

------BoundaryDelimitadorHttp
Content-Disposition: form-data; name="file"; filename="foto.jpg"
Content-Type: image/jpeg

< ./dev/images/foto.jpg
------BoundaryDelimitadorHttp--

### ver foto
GET {{Url}}/pictures/23.jpg